ARG GITHUB_TOKEN
FROM node:16.17.0-alpine AS build
ARG GITHUB_TOKEN
ENV GITHUB_TOKEN $GITHUB_TOKEN
WORKDIR /app
RUN echo //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN >> ~/.npmrc
RUN echo @moxfive-llc:registry=https://npm.pkg.github.com/ >> ~/.npmrc
COPY package.json .
RUN npm install
COPY . .

CMD ["npm", "run", "dev:local"]
